---
- name: Prepare Servers for Docker Deployment
  hosts: all
  become: yes  # Required to gain root privileges

  tasks:
    - name: Install Docker on AWS Linux
      yum:
        name: docker
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull latest Docker image
      docker_image:
        name: "buffy1809/myapp"
        tag: "latest"
        source: pull

    - name: Remove existing Docker container
      docker_container:
        name: myapp
        state: absent

    - name: Create Docker container
      docker_container:
        name: myapp
        image: "buffy1809/myapp:latest"
        state: started
        recreate: yes
        published_ports:
          - "{{ item }}"
      with_items:
        - "80:80"  # For testing server
        - "8081:80"  # For production server
