global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape node-exporter for server metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['44.223.169.199:9100']

  # Scrape Flask app for application metrics
  - job_name: 'flask-app'
     # Assuming you've integrated the metrics into your Flask app
    static_configs:
      - targets: ['44.223.169.199:80']  # Or replace with the appropriate port of your Flask app