- name: Config docker and docker compose
  hosts: test,prod
  become: true
  tasks:

  - name: Install docker
    command: amazon-linux-extras install docker=latest -y
    args:
      creates: /usr/bin/docker

  - name: Create directory for docker plugins
    file:
      path: /usr/local/lib/docker/cli-plugins
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Download docker compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
      dest: /usr/local/lib/docker/cli-plugins/docker-compose
      mode: 0755

  - name: Ensure docker is running
    systemd:
      name: docker
      state: started
      enabled: true
